# Generated by Django 6.0.3 on 2026-03-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage_files',
            new_name='StorageFiles',
        ),
    ]
