# Generated by Django 6.0.3 on 2026-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filestorage', '0002_rename_storage_files_storagefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefiles',
            name='file_name_storage',
            field=models.CharField(max_length=32),
        ),
    ]
